# Generated by Django 4.1.2 on 2022-12-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='remuf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buku', models.CharField(max_length=100)),
                ('Penulis', models.CharField(max_length=50)),
                ('Penerbit', models.CharField(max_length=50)),
                ('Jumlah', models.IntegerField(null=True)),
            ],
        ),
    ]
